gtnh.settings.blowdryerTag = 0.2.2
modName = Unchanged World
modId = unchangedworld
modGroup = com.sxilverr.unchangedworld
useModGroupForPublishing = true
autoUpdateBuildScript = false
minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614
channel = stable
mappingsVersion = 12
remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/
developmentEnvironmentUserName = Developer
enableModernJavaSyntax = jabel
enableGenericInjection = true
generateGradleTokenClass = com.sxilverr.unchangedworld.Tags
gradleTokenVersion = VERSION
replaceGradleTokenInFile =
apiPackage =
accessTransformersFile =
usesMixins = true
separateMixinSourceSet =
usesMixinDebug = false
mixinPlugin =
mixinsPackage = mixins
coreModClass =
containsMixinsAndOrCoreModOnly = false
forceEnableMixins = false
usesShadowedDependencies = false
minimizeShadowedDependencies = true
relocateShadowedDependencies = true
includeWellKnownRepositories = true
excludeWellKnownRepositories =
usesMavenPublishing = true
modrinthProjectId =
modrinthRelations =
curseForgeProjectId =
curseForgeRelations =
org.gradle.configuration-cache = true
org.gradle.parallel = true
